import type { ProjectIndexProgramEnvelope } from "@/lib/projectIndex";

/**
 * Normalise MCP result content into a plain object.
 * Same pattern used by the existing built-in Studio programs.
 * Kept inline because these sources run in the generated program sandbox.
 */
const NORMALIZE_MCP_RESULT = `
function normalizeMcpResult(result: unknown): any {
  const content = result && typeof result === "object" && !Array.isArray(result)
    ? (result as any).content
    : result;
  if (Array.isArray(content)) {
    for (const part of content) {
      if (!part || typeof part !== "object") continue;
      if ((part as any).type === "json") return (part as any).json;
      if ((part as any).type === "text" && typeof (part as any).text === "string") {
        try { return JSON.parse((part as any).text); } catch { return (part as any).text; }
      }
    }
  }
  if (typeof content === "string") {
    try { return JSON.parse(content); } catch { return content; }
  }
  return content;
}`;

/**
 * Inline Luau require() parser that runs inside the Roblox Studio sandbox.
 * This mirrors parseRequireCalls from the TS side but runs in the generated program.
 */
const REQUIRE_PARSER = `
function parseRequires(source) {
  const deps = [];
  // Match require(...) capturing the inner expression.
  // Handles nested parens used by :GetService("Foo").
  const re = /require\\s*\\(\\s*((?:[^()]+|\\([^()]*\\))+)\\s*\\)/g;
  let m;
  while ((m = re.exec(source)) !== null) {
    let expr = m[1].trim();
    if (!expr) continue;
    // Strip whitespace inside the expression.
    expr = expr.replace(/\\s+/g, "");
    // If it's a string literal, extract the value.
    if (
      (expr.startsWith('"') && expr.endsWith('"')) ||
      (expr.startsWith("'") && expr.endsWith("'"))
    ) {
      deps.push(expr.slice(1, -1));
      continue;
    }
    // Normalise game:GetService("X") -> game.X
    expr = expr.replace(/game\\s*:\\s*GetService\\s*\\(\\s*["']([^"']+)["']\\s*\\)/g, "game.$1");
    // Tag simple variable references with var: prefix (lowercase, no dots/colons)
    if (/^[a-z_][a-zA-Z0-9_]*$/.test(expr)) {
      deps.push("var:" + expr);
      continue;
    }
    // Normalize capitalized service paths (e.g. ReplicatedStorage.Foo) to game. prefix
    if (!expr.startsWith("game.") && !expr.startsWith("script") && /^[A-Z]/.test(expr)) {
      expr = "game." + expr;
    }
    deps.push(expr);
  }
  return deps;
}`;

/**
 * Detect whether a script's source code is worth indexing.
 * We skip generated code, roblox-created content, and empty scripts.
 */
const SCRIPT_FILTER = `
function isIndexable(source, className) {
  if (!source || source.length < 10) return false;
  // Skip generated/locked modules that are typically engine code.
  if (source.indexOf("-- Generated by Rojo") !== -1) return false;
  if (source.indexOf("--!nocheck") === 0) return false;
  return true;
}`;

const projectIndexSource = `
${NORMALIZE_MCP_RESULT}
${REQUIRE_PARSER}
${SCRIPT_FILTER}
async function run({ callTool }: { input: unknown; callTool: (name: string, args: Record<string, unknown>) => Promise<unknown> }) {
  // Discover all script-type instances in the place.
  // We search the full game tree at max depth to catch deeply nested modules.
  const scriptClasses = ["Script", "ModuleScript", "LocalScript", "BaseScript"];
  const raw = normalizeMcpResult(
    await callTool("search_game_tree", { max_depth: 10, head_limit: 100000 })
  );
  const rows = Array.isArray(raw) ? raw : Array.isArray(raw?.instances) ? raw.instances : [];
  // Built-in services that typically hold user scripts.
  const visibleServices = new Set([
    "Workspace", "Players", "ReplicatedFirst", "ReplicatedStorage",
    "ServerScriptService", "ServerStorage", "StarterGui",
    "StarterPack", "StarterPlayer", "Chat", "Teams",
  ]);

  const modules = [];
  const byPath = new Map();

  for (const row of rows) {
    const className = typeof row.className === "string" ? row.className : "";
    if (!scriptClasses.includes(className)) continue;
    if (!visibleServices.has((row.fullPath ?? row.path ?? "").split(".")[0])) continue;

    const path = typeof row.fullPath === "string" ? row.fullPath
      : typeof row.path === "string" ? row.path : "";
    if (!path) continue;

    const instanceName = typeof row.name === "string" && row.name ? row.name
      : typeof row.Name === "string" && row.Name ? row.Name
      : typeof row.properties?.Name === "string" && row.properties?.Name ? row.properties.Name
      : path.split(".").at(-1) ?? path;

    // Read the actual script source via MCP.
    let source = null;
    try {
      const scriptPath = path.startsWith("game.") ? path : "game." + path;
      const scriptData = normalizeMcpResult(
        await callTool("read_script", { script_path: scriptPath })
      );
      // The result may be { source: "..." } or just the source string.
      if (typeof scriptData === "string") source = scriptData;
      else if (scriptData?.source && typeof scriptData.source === "string") source = scriptData.source;
      else if (scriptData?.content && typeof scriptData.content === "string") source = scriptData.content;
    } catch {
      // Can't read this script, skip it.
      continue;
    }

    if (!isIndexable(source, className)) continue;

    const deps = parseRequires(source);
    const qualifiedPath = path.startsWith("game.") ? path : "game." + path;

    byPath.set(qualifiedPath, {
      path: qualifiedPath,
      name: instanceName,
      className: className,
      sourceLength: source.length,
      dependencies: deps,
    });
  }

  // Build into an ordered list sorted by path for deterministic output.
  const allModules = [...byPath.values()].sort((a, b) => a.path.localeCompare(b.path));

  // Count by type.
  let totalScripts = 0;
  let totalModuleScripts = 0;
  for (const mod of allModules) {
    if (mod.className === "ModuleScript") totalModuleScripts++;
    else totalScripts++;
  }

  // Detect entry points: modules not required by any other known module.
  const requiredBy = new Map();
  for (const mod of allModules) {
    for (const dep of mod.dependencies) {
      if (!requiredBy.has(dep)) requiredBy.set(dep, new Set());
      requiredBy.get(dep).add(mod.path);
    }
  }
  const entryPoints = allModules
    .filter((mod) => !requiredBy.has(mod.path) || requiredBy.get(mod.path).size === 0)
    .map((mod) => mod.path);

  // Detect circular dependencies via DFS.
  const circularDeps = [];
  const visited = new Set();
  const inStack = new Set();
  const pathMap = new Map();
  for (const mod of allModules) pathMap.set(mod.path, mod);

  function dfs(current) {
    if (inStack.has(current)) return;
    if (visited.has(current)) return;
    visited.add(current);
    inStack.add(current);
    const mod = pathMap.get(current);
    if (mod) {
      for (const dep of mod.dependencies) {
        if (pathMap.has(dep)) {
          if (inStack.has(dep)) {
            circularDeps.push([current, dep]);
          } else {
            dfs(dep);
          }
        }
      }
    }
    inStack.delete(current);
  }
  for (const mod of allModules) dfs(mod.path);

  return {
    modules: allModules,
    entryPoints,
    circularDependencies: circularDeps,
    totalScripts,
    totalModuleScripts,
  };
}`;

/**
 * Built-in project index program that runs locally via the GeneratedProgramRuntime.
 * When the AI-generated version isn't available, this provides a reasonable
 * dependency map using the same MCP tools the AI would use.
 */
export const BUILTIN_PROJECT_INDEX_PROGRAM: ProjectIndexProgramEnvelope = {
  version: 1,
  contract: {
    name: "project-index",
    version: "1",
    inputSchemaVersion: "project-index-input-v1",
    outputSchemaVersion: "project-index-skeleton-v1",
  },
  source: projectIndexSource,
};