import type { ProjectIndexProgramEnvelope } from "@/lib/projectIndex";

// ── Inline sandbox helpers ───────────────────────────────────────────────
//
// The following constants are embedded as raw strings inside the generated
// program source. They run inside the Roblox Studio sandbox (not the Electron
// renderer), so they must be self-contained and import-free.

/**
 * Normalise MCP result content into a plain object.
 *
 * MCP tools return results in various shapes: `{ content: [...] }`, raw
 * arrays, JSON strings, or plain objects. This helper unwraps the common
 * `content` array format (extracting `json` or `text` parts) and falls back
 * to JSON-parsing string content.
 *
 * Same pattern used by the existing built-in Studio programs.
 * Kept inline because these sources run in the generated program sandbox.
 */
const NORMALIZE_MCP_RESULT = `
function normalizeMcpResult(result: unknown): any {
  const content = result && typeof result === "object" && !Array.isArray(result)
    ? (result as any).content
    : result;
  if (Array.isArray(content)) {
    for (const part of content) {
      if (!part || typeof part !== "object") continue;
      if ((part as any).type === "json") return (part as any).json;
      if ((part as any).type === "text" && typeof (part as any).text === "string") {
        try { return JSON.parse((part as any).text); } catch { return (part as any).text; }
      }
    }
  }
  if (typeof content === "string") {
    try { return JSON.parse(content); } catch { return content; }
  }
  return content;
}`;

/**
 * Inline Luau comment stripper + `require()` parser that runs inside the
 * Roblox Studio sandbox.
 *
 * This mirrors `stripLuauComments` + `parseRequireCalls` from the TS side
 * (`src/lib/projectIndex.ts`) but is written as plain JavaScript since it
 * runs in the generated program sandbox without TypeScript compilation.
 *
 * - `stripComments(source)` — removes `--[[ ... ]]` block comments and
 *   `-- ...` line comments (respecting string literals).
 * - `parseRequires(source)` — extracts canonical dependency keys from all
 *   `require()` calls, normalising `game:GetService("X")` to `game.X` and
 *   tagging variable references with `var:`.
 */
const REQUIRE_PARSER = `
function stripComments(source) {
  // Remove block comments --[[ ... ]] (non-greedy, multiline).
  let result = source.replace(/--\\[\\[[\\s\\S]*?\\]\\]/g, "");
  // Remove line comments respecting string literals.
  const lines = result.split("\\n");
  for (let i = 0; i < lines.length; i++) {
    let inSingle = false, inDouble = false;
    const line = lines[i];
    for (let j = 0; j < line.length - 1; j++) {
      const ch = line[j], next = line[j + 1];
      if (inSingle) { if (ch === "\\\\") { j++; continue; } if (ch === "'") inSingle = false; continue; }
      if (inDouble) { if (ch === "\\\\") { j++; continue; } if (ch === '"') inDouble = false; continue; }
      if (ch === '"') { inDouble = true; continue; }
      if (ch === "'") { inSingle = true; continue; }
      if (ch === "-" && next === "-") { lines[i] = line.slice(0, j); break; }
    }
  }
  return lines.join("\\n");
}

function parseRequires(source) {
  const deps = [];
  const cleaned = stripComments(source);
  // Match require(...) capturing the inner expression.
  // Handles nested parens used by :GetService("Foo").
  const re = /require\\s*\\(\\s*((?:[^()]+|\\([^()]*\\))+)\\s*\\)/g;
  let m;
  while ((m = re.exec(cleaned)) !== null) {
    let expr = m[1].trim();
    if (!expr) continue;
    // Strip whitespace inside the expression.
    expr = expr.replace(/\\s+/g, "");
    // If it's a string literal, extract the value.
    if (
      (expr.startsWith('"') && expr.endsWith('"')) ||
      (expr.startsWith("'") && expr.endsWith("'"))
    ) {
      deps.push(expr.slice(1, -1));
      continue;
    }
    // Normalise game:GetService("X") -> game.X
    expr = expr.replace(/game\\s*:\\s*GetService\\s*\\(\\s*["']([^"']+)["']\\s*\\)/g, "game.$1");
    // Tag simple variable references with var: prefix (lowercase, no dots/colons)
    if (/^[a-z_][a-zA-Z0-9_]*$/.test(expr)) {
      deps.push("var:" + expr);
      continue;
    }
    // Normalize capitalized service paths (e.g. ReplicatedStorage.Foo) to game. prefix
    if (!expr.startsWith("game.") && !expr.startsWith("script") && /^[A-Z]/.test(expr)) {
      expr = "game." + expr;
    }
    deps.push(expr);
  }
  return deps;
}`;

/**
 * Detect whether a script's source code is worth indexing.
 *
 * Skips:
 * - Empty or very short sources (< 10 chars)
 * - Rojo-generated modules (`-- Generated by Rojo`)
 * - Type-check-disabled scripts (`--!nocheck`)
 */
const SCRIPT_FILTER = `
function isIndexable(source, className) {
  if (!source || source.length < 10) return false;
  // Skip generated/locked modules that are typically engine code.
  if (source.indexOf("-- Generated by Rojo") !== -1) return false;
  if (source.indexOf("--!nocheck") === 0) return false;
  return true;
}`;

// ── Program source ───────────────────────────────────────────────────────

/**
 * The full built-in project index program source.
 *
 * This string is compiled and executed by the `GeneratedProgramRuntime`.
 * It discovers all script-type instances in the place via the
 * `search_game_tree` MCP tool, reads each script's source via `read_script`,
 * parses `require()` calls, and builds a dependency graph with:
 * - Entry point detection (modules nothing depends on)
 * - Circular dependency detection (DFS with stack tracing)
 * - Dependency depth computation (memoised, cycle-safe)
 * - Dependents count for each module
 *
 * The program is read-only and never modifies the place.
 */
const projectIndexSource = `
${NORMALIZE_MCP_RESULT}
${REQUIRE_PARSER}
${SCRIPT_FILTER}
async function run({ callTool }: { input: unknown; callTool: (name: string, args: Record<string, unknown>) => Promise<unknown> }) {
  // Discover all script-type instances in the place.
  // We search the full game tree at max depth to catch deeply nested modules.
  const scriptClasses = ["Script", "ModuleScript", "LocalScript", "BaseScript"];
  const raw = normalizeMcpResult(
    await callTool("search_game_tree", {
      datamodel_type: "place",
      max_depth: 10,
      head_limit: 100000,
    })
  );
  const rows = Array.isArray(raw) ? raw : Array.isArray(raw?.instances) ? raw.instances : [];
  // Built-in services that typically hold user scripts.
  const visibleServices = new Set([
    "Workspace", "Players", "ReplicatedFirst", "ReplicatedStorage",
    "ServerScriptService", "ServerStorage", "StarterGui",
    "StarterPack", "StarterPlayer", "Chat", "Teams",
  ]);

  const byPath = new Map();

  for (const row of rows) {
    const className = typeof row.className === "string" ? row.className : "";
    if (!scriptClasses.includes(className)) continue;
    if (!visibleServices.has((row.fullPath ?? row.path ?? "").split(".")[0])) continue;

    const path = typeof row.fullPath === "string" ? row.fullPath
      : typeof row.path === "string" ? row.path : "";
    if (!path) continue;

    // Resolve the instance name with the same fallback chain as the Explorer program:
    // row.properties.Name -> row.Name -> row.name -> last path segment.
    const properties = row?.properties && typeof row.properties === "object" ? row.properties : {};
    const instanceName =
      typeof properties.Name === "string" && properties.Name ? properties.Name :
      typeof row.Name === "string" && row.Name ? row.Name :
      typeof row.name === "string" && row.name ? row.name :
      path.split(".").at(-1) ?? path;

    // Read the actual script source via MCP.
    let source = null;
    try {
      const scriptPath = path.startsWith("game.") ? path : "game." + path;
      const scriptData = normalizeMcpResult(
        await callTool("read_script", { script_path: scriptPath })
      );
      // The result may be { source: "..." } or just the source string.
      if (typeof scriptData === "string") source = scriptData;
      else if (scriptData?.source && typeof scriptData.source === "string") source = scriptData.source;
      else if (scriptData?.content && typeof scriptData.content === "string") source = scriptData.content;
    } catch {
      // Can't read this script, skip it.
      continue;
    }

    if (!isIndexable(source, className)) continue;

    const deps = parseRequires(source);
    const qualifiedPath = path.startsWith("game.") ? path : "game." + path;

    byPath.set(qualifiedPath, {
      path: qualifiedPath,
      name: instanceName,
      className: className,
      sourceLength: source.length,
      dependencies: deps,
    });
  }

  // Build into an ordered list sorted by path for deterministic output.
  const allModules = [...byPath.values()].sort((a, b) => a.path.localeCompare(b.path));

  // Count by type.
  let totalScripts = 0;
  let totalModuleScripts = 0;
  for (const mod of allModules) {
    if (mod.className === "ModuleScript") totalModuleScripts++;
    else totalScripts++;
  }

  // Detect entry points: modules not required by any other known module.
  // Also compute dependentsCount for each module.
  const requiredBy = new Map();
  for (const mod of allModules) {
    for (const dep of mod.dependencies) {
      if (!requiredBy.has(dep)) requiredBy.set(dep, new Set());
      requiredBy.get(dep).add(mod.path);
    }
  }
  const entryPoints = allModules
    .filter((mod) => !requiredBy.has(mod.path) || requiredBy.get(mod.path).size === 0)
    .map((mod) => mod.path);

  // Detect circular dependencies via DFS, deduplicating by canonical cycle key.
  // Also collect all nodes that participate in any cycle by tracing the recursion
  // stack when a back-edge is found.
  const seenCycles = new Set();
  const circularDeps = [];
  const visited = new Set();
  const inStack = new Set();
  const stackArr = [];
  const cycleMembers = new Set();
  const pathMap = new Map();
  for (const mod of allModules) pathMap.set(mod.path, mod);

  function dfs(current) {
    if (inStack.has(current)) return;
    if (visited.has(current)) return;
    visited.add(current);
    inStack.add(current);
    stackArr.push(current);
    const mod = pathMap.get(current);
    if (mod) {
      for (const dep of mod.dependencies) {
        if (pathMap.has(dep)) {
          if (inStack.has(dep)) {
            const key = [current, dep].sort().join("\\u2194");
            if (!seenCycles.has(key)) {
              seenCycles.add(key);
              circularDeps.push([current, dep]);
            }
            // Mark all nodes on the stack between dep and current as cycle members.
            const idx = stackArr.indexOf(dep);
            if (idx !== -1) {
              for (let i = idx; i < stackArr.length; i++) {
                cycleMembers.add(stackArr[i]);
              }
            }
          } else {
            dfs(dep);
          }
        }
      }
    }
    inStack.delete(current);
    stackArr.pop();
  }
  for (const mod of allModules) dfs(mod.path);

  // Compute dependency depth via memoised DFS on resolved dependencies.
  // Cycle members get depth 0 to avoid infinite recursion and inflated values.
  const depthCache = new Map();
  const computing = new Set();
  function computeDepth(path) {
    if (depthCache.has(path)) return depthCache.get(path);
    if (cycleMembers.has(path)) { depthCache.set(path, 0); return 0; }
    if (computing.has(path)) return -1;
    computing.add(path);
    const mod = pathMap.get(path);
    let maxDepDepth = 0;
    if (mod) {
      for (const dep of mod.dependencies) {
        if (pathMap.has(dep)) {
          const depDepth = computeDepth(dep);
          if (depDepth >= 0 && depDepth + 1 > maxDepDepth) maxDepDepth = depDepth + 1;
        }
      }
    }
    computing.delete(path);
    depthCache.set(path, maxDepDepth);
    return maxDepDepth;
  }

  // Enrich modules with computed graph fields.
  const enrichedModules = allModules.map(function (mod) {
    return {
      path: mod.path,
      name: mod.name,
      className: mod.className,
      sourceLength: mod.sourceLength,
      dependencies: mod.dependencies,
      dependentsCount: (requiredBy.get(mod.path) || new Set()).size,
      dependencyDepth: computeDepth(mod.path),
    };
  });

  return {
    modules: enrichedModules,
    entryPoints,
    circularDependencies: circularDeps,
    totalScripts,
    totalModuleScripts,
  };
}`;

// ── Exported envelope ────────────────────────────────────────────────────

/**
 * Built-in project index program that runs locally via the
 * `GeneratedProgramRuntime`.
 *
 * When the AI-generated version isn't available (or fails to generate),
 * this provides a reasonable dependency map using the same MCP tools the
 * AI would use. The program is read-only and never modifies the place.
 */
export const BUILTIN_PROJECT_INDEX_PROGRAM: ProjectIndexProgramEnvelope = {
  version: 1,
  contract: {
    name: "project-index",
    version: "1",
    inputSchemaVersion: "project-index-input-v1",
    outputSchemaVersion: "project-index-skeleton-v1",
  },
  source: projectIndexSource,
};
