export const channels = {
  compileExplorerProgram: "explorer:compile-program",
  checkForUpdate: "app:check-for-update",
  getOpenCodeInfo: "opencode:get-info",
  openCodeStartupProgress: "opencode:startup-progress",
  getVersion: "app:get-version",
  installUpdate: "app:install-update",
  invokeExplorerProgram: "explorer:invoke-program",
  loadConfig: "config:load",
  openUrl: "app:open-url",
  patchConfig: "config:patch",
  relaunch: "app:relaunch",
  discoverStudioTargets: "studio-target:discover",
  installStudioTargetPrograms: "studio-target:install-programs",
  selectStudioTarget: "studio-target:select",
  compileProjectIndexProgram: "project-index:compile-program",
  invokeProjectIndexProgram: "project-index:invoke-program",
  // ── Checkpoint system ──────────────────────────────────────────────
  checkpointCapture: "checkpoint:capture",
  checkpointRestore: "checkpoint:restore",
  checkpointPreview: "checkpoint:preview",
  checkpointList: "checkpoint:list",
  checkpointValidate: "checkpoint:validate",
  // ── Rojo live-sync ─────────────────────────────────────────────────
  rojoStatus: "rojo:status",
  rojoToggle: "rojo:toggle",
  rojoLogs: "rojo:logs",
  rojoStart: "rojo:start",
  rojoStop: "rojo:stop",
  onRojoLog: "rojo:on-log",
  // ── Rojo 1-click setup ─────────────────────────────────────────────
  rojoSetup: "rojo:setup",
  rojoSetupProgress: "rojo:setup-progress",
  rojoBinaryPath: "rojo:binary-path",
  rojoCheckInstalled: "rojo:check-installed",
} as const;
